routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index');

Route::get('/frontend/{id}', 'FrontendController@show');

// Route::get('/register', function () {
//     return view('frontend.register');
// });

Route::resource('posts', 'PostController')->middleware('auth');
Route::resource('comments', 'CommentController')->middleware('auth');
Route::resource('categories', 'CategoryController')->middleware('auth');
Route::resource('profiles', 'ProfileController')->middleware('auth');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/layouts/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Profile Dropdown Menu -->
    <li class="dropdown user user-menu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src='{{ asset("images/".Auth::user()->profile->avatar) }}' class="user-image" alt="User Image"
          style="width: 33.59px; height: 33.59px; object-fit:cover">
        <span class="hidden-xs">{{ Auth::user()->profile->fullname }}</span>
      </a>
      <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
          <img src="{{ asset("images/".Auth::user()->profile->avatar) }}" class="img-circle" alt="User Image"
            style="width: 90px; height: 90px; object-fit:cover">

          <p>
            {{ Auth::user()->profile->fullname }}
            <small>Member since {{ Auth::user()->profile->created_at }}</small>
          </p>
        </li>
        <!-- Menu Footer-->
        <li class="user-footer" style="text-align: center">
          <a href="/profiles/{{ Auth::user()->id }}/edit" class="btn btn-default btn-flat">Profile</a>
          <a class="btn btn-default btn-flat" href="{{ route('logout') }}" onclick="event.preventDefault();
          document.getElementById('logout-form').submit();">
            {{ __('Logout') }}</a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
          </form>
        </li>
      </ul>
    </li>
  </ul>
</nav>

resources/views/backend/layouts/partials/sidebar.blade.php
{{-- <a href="#" class="d-block">{{ Auth::user()->name }}</a> --}}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="{{ asset('backend/index3.html') }}" class="brand-link">
    <img src="{{ asset('backend/dist/img/AdminLTELogo.png') }}" alt="TravelBlog Logo"
      class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">TravelBlog</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{ asset("images/".Auth::user()->profile->avatar) }}" class="img-circle elevation-2" alt="User Image"
          style="width: 33.59px; height: 33.59px; object-fit:cover">
      </div>
      <div class="info">
        <a href="#" class="d-block">{{ Auth::user()->profile->fullname }}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="/" class="nav-link">
            <i class="nav-icon fab fa-blogger"></i>
            <p>
              Blogs
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('posts.index') }}" class="nav-link">
            <i class="nav-icon far fa-file-alt"></i>
            <p>
              Posts
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('comments.index') }}" class="nav-link">
            <i class="nav-icon far fa-comments"></i>
            <p>
              Comments
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('categories.index') }}" class="nav-link">
            <i class="nav-icon fab fa-buffer"></i>
            <p>
              Categories
            </p>
          </a>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>